export const UPDATE_DRAFT="write/UPDATE_DRAFT"
export const CHANGE_TOPIC="write/CHANGE_TOPIC"
export const CHANGE_DOMAIN="write/CHANGE_DOMAIN"
export const GET_DOMAINS="write/GET_DOMAINS"
export const GET_TOPICS="write/GET_TOPICS"
export const SET_SELECTED_TOPIC="write/SET_SELECTED_TOPIC"
export const COMMIT_ARTICLE="write/COMMIT_ARTICLE"